# Generated by Django 5.1.15 on 2026-08-18 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trail_name', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('date_hiked', models.DateField()),
                ('distance_miles', models.DecimalField(decimal_places=2, max_digits=6)),
                ('elevation_gain_ft', models.PositiveIntegerField(default=0)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard'), ('strenuous', 'Strenuous')], default='moderate', max_length=10)),
                ('rating', models.PositiveSmallIntegerField(default=3)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hikes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_hiked', '-created_at'],
            },
        ),
    ]
